// NextGenX Theme System - Multiple Color Schemes
// Clean, modern design with customizable color themes

export const spacing = {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
};

export const borderRadius = {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    round: 50,
};

export const fontSize = {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 24,
    xxl: 32,
    xxxl: 40,
};

export const fontWeight = {
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
};

// Theme Definitions
export const themes = {
    // Classic Black & White
    classic: {
        light: {
            name: 'Classic Light',
            primary: '#000000',
            primaryLight: '#333333',
            primaryDark: '#000000',
            accent: '#FFFFFF',
            accent2: '#F5F5F5',
            accent3: '#E8E8E8',
            background: '#FFFFFF',
            backgroundSecondary: '#F8F8F8',
            backgroundCard: '#FFFFFF',
            text: '#000000',
            textSecondary: '#666666',
            textInverse: '#FFFFFF',
            textMuted: '#999999',
            border: '#E0E0E0',
            borderLight: '#F0F0F0',
            borderDark: '#D0D0D0',
            shadow: 'rgba(0, 0, 0, 0.1)',
            shadowDark: 'rgba(0, 0, 0, 0.15)',
            success: '#000000',
            error: '#000000',
            warning: '#000000',
            info: '#000000',
        },
        dark: {
            name: 'Classic Dark',
            primary: '#FFFFFF',
            primaryLight: '#E8EAED',
            primaryDark: '#FFFFFF',
            accent: '#292a2d',
            accent2: '#35363a',
            accent3: '#3c4043',
            background: '#202124',
            backgroundSecondary: '#292a2d',
            backgroundCard: '#292a2d',
            text: '#E8EAED',
            textSecondary: '#9AA0A6',
            textInverse: '#202124',
            textMuted: '#5F6368',
            border: '#3c4043',
            borderLight: '#5F6368',
            borderDark: '#292a2d',
            shadow: 'rgba(0, 0, 0, 0.3)',
            shadowDark: 'rgba(0, 0, 0, 0.5)',
            success: '#81C995',
            error: '#F28B82',
            warning: '#FDD663',
            info: '#8AB4F8',
        },
    },

    // Neon Blue
    neonBlue: {
        light: {
            name: 'Neon Blue Light',
            primary: '#0066FF',
            primaryLight: '#3385FF',
            primaryDark: '#0052CC',
            accent: '#00D4FF',
            accent2: '#E6F7FF',
            accent3: '#CCF0FF',
            background: '#FFFFFF',
            backgroundSecondary: '#F5FAFF',
            backgroundCard: '#FFFFFF',
            text: '#000000',
            textSecondary: '#4A5568',
            textInverse: '#FFFFFF',
            textMuted: '#718096',
            border: '#E2E8F0',
            borderLight: '#EDF2F7',
            borderDark: '#CBD5E0',
            shadow: 'rgba(0, 102, 255, 0.1)',
            shadowDark: 'rgba(0, 102, 255, 0.2)',
            success: '#00C853',
            error: '#FF1744',
            warning: '#FFC400',
            info: '#0066FF',
        },
        dark: {
            name: 'Neon Blue Dark',
            primary: '#0066FF',
            primaryLight: '#3385FF',
            primaryDark: '#0052CC',
            accent: '#00D4FF',
            accent2: '#292a2d',
            accent3: '#3c4043',
            background: '#202124',
            backgroundSecondary: '#292a2d',
            backgroundCard: '#292a2d',
            text: '#E8EAED',
            textSecondary: '#9AA0A6',
            textInverse: '#202124',
            textMuted: '#5F6368',
            border: '#3c4043',
            borderLight: '#5F6368',
            borderDark: '#292a2d',
            shadow: 'rgba(0, 102, 255, 0.2)',
            shadowDark: 'rgba(0, 102, 255, 0.3)',
            success: '#81C995',
            error: '#F28B82',
            warning: '#FDD663',
            info: '#0066FF',
        },
    },

    // Purple Dream
    purpleDream: {
        light: {
            name: 'Purple Dream Light',
            primary: '#7C3AED',
            primaryLight: '#9F67FF',
            primaryDark: '#6D28D9',
            accent: '#EC4899',
            accent2: '#F3E8FF',
            accent3: '#E9D5FF',
            background: '#FFFFFF',
            backgroundSecondary: '#FAF5FF',
            backgroundCard: '#FFFFFF',
            text: '#1F2937',
            textSecondary: '#6B7280',
            textInverse: '#FFFFFF',
            textMuted: '#9CA3AF',
            border: '#E5E7EB',
            borderLight: '#F3F4F6',
            borderDark: '#D1D5DB',
            shadow: 'rgba(124, 58, 237, 0.1)',
            shadowDark: 'rgba(124, 58, 237, 0.2)',
            success: '#10B981',
            error: '#EF4444',
            warning: '#F59E0B',
            info: '#7C3AED',
        },
        dark: {
            name: 'Purple Dream Dark',
            primary: '#A78BFA',
            primaryLight: '#C4B5FD',
            primaryDark: '#8B5CF6',
            accent: '#F472B6',
            accent2: '#292a2d',
            accent3: '#3c4043',
            background: '#202124',
            backgroundSecondary: '#292a2d',
            backgroundCard: '#292a2d',
            text: '#E8EAED',
            textSecondary: '#9AA0A6',
            textInverse: '#202124',
            textMuted: '#5F6368',
            border: '#3c4043',
            borderLight: '#5F6368',
            borderDark: '#292a2d',
            shadow: 'rgba(167, 139, 250, 0.2)',
            shadowDark: 'rgba(167, 139, 250, 0.3)',
            success: '#81C995',
            error: '#F28B82',
            warning: '#FDD663',
            info: '#A78BFA',
        },
    },

    // Emerald Green
    emeraldGreen: {
        light: {
            name: 'Emerald Light',
            primary: '#059669',
            primaryLight: '#10B981',
            primaryDark: '#047857',
            accent: '#34D399',
            accent2: '#D1FAE5',
            accent3: '#A7F3D0',
            background: '#FFFFFF',
            backgroundSecondary: '#F0FDF4',
            backgroundCard: '#FFFFFF',
            text: '#1F2937',
            textSecondary: '#4B5563',
            textInverse: '#FFFFFF',
            textMuted: '#6B7280',
            border: '#E5E7EB',
            borderLight: '#F3F4F6',
            borderDark: '#D1D5DB',
            shadow: 'rgba(5, 150, 105, 0.1)',
            shadowDark: 'rgba(5, 150, 105, 0.2)',
            success: '#059669',
            error: '#DC2626',
            warning: '#D97706',
            info: '#0891B2',
        },
        dark: {
            name: 'Emerald Dark',
            primary: '#10B981',
            primaryLight: '#34D399',
            primaryDark: '#059669',
            accent: '#6EE7B7',
            accent2: '#292a2d',
            accent3: '#3c4043',
            background: '#202124',
            backgroundSecondary: '#292a2d',
            backgroundCard: '#292a2d',
            text: '#E8EAED',
            textSecondary: '#9AA0A6',
            textInverse: '#202124',
            textMuted: '#5F6368',
            border: '#3c4043',
            borderLight: '#5F6368',
            borderDark: '#292a2d',
            shadow: 'rgba(16, 185, 129, 0.2)',
            shadowDark: 'rgba(16, 185, 129, 0.3)',
            success: '#10B981',
            error: '#F28B82',
            warning: '#FDD663',
            info: '#8AB4F8',
        },
    },

    // Sunset Orange
    sunsetOrange: {
        light: {
            name: 'Sunset Light',
            primary: '#EA580C',
            primaryLight: '#FB923C',
            primaryDark: '#C2410C',
            accent: '#FBBF24',
            accent2: '#FFF7ED',
            accent3: '#FFEDD5',
            background: '#FFFFFF',
            backgroundSecondary: '#FFFBF5',
            backgroundCard: '#FFFFFF',
            text: '#1F2937',
            textSecondary: '#4B5563',
            textInverse: '#FFFFFF',
            textMuted: '#6B7280',
            border: '#E5E7EB',
            borderLight: '#F3F4F6',
            borderDark: '#D1D5DB',
            shadow: 'rgba(234, 88, 12, 0.1)',
            shadowDark: 'rgba(234, 88, 12, 0.2)',
            success: '#16A34A',
            error: '#DC2626',
            warning: '#EA580C',
            info: '#0284C7',
        },
        dark: {
            name: 'Sunset Dark',
            primary: '#FB923C',
            primaryLight: '#FDBA74',
            primaryDark: '#EA580C',
            accent: '#FCD34D',
            accent2: '#292a2d',
            accent3: '#3c4043',
            background: '#202124',
            backgroundSecondary: '#292a2d',
            backgroundCard: '#292a2d',
            text: '#E8EAED',
            textSecondary: '#9AA0A6',
            textInverse: '#202124',
            textMuted: '#5F6368',
            border: '#3c4043',
            borderLight: '#5F6368',
            borderDark: '#292a2d',
            shadow: 'rgba(251, 146, 60, 0.2)',
            shadowDark: 'rgba(251, 146, 60, 0.3)',
            success: '#81C995',
            error: '#F28B82',
            warning: '#FB923C',
            info: '#8AB4F8',
        },
    },
};

// Shadow Styles
export const shadows = {
    small: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    medium: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 4,
    },
    large: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 16,
        elevation: 8,
    },
};

// Helper function to get theme
export const getTheme = (themeName, isDark) => {
    const themeData = themes[themeName] || themes.classic;
    return isDark ? themeData.dark : themeData.light;
};

// Export theme names for settings
export const themeNames = Object.keys(themes);
